// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package hudi

import (
	"bufio"
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

// Property keys used in a Hudi table's .hoodie/hoodie.properties file.
const (
	PropTableName             = "hoodie.table.name"
	PropTableType             = "hoodie.table.type"
	PropTableVersion          = "hoodie.table.version"
	PropBaseFileFormat        = "hoodie.table.base.file.format"
	PropPartitionFields       = "hoodie.table.partition.fields"
	PropRecordKeyFields       = "hoodie.table.recordkey.fields"
	PropKeyGeneratorClass     = "hoodie.table.keygenerator.class"
	PropPrecombineField       = "hoodie.table.precombine.field"
	PropChecksum              = "hoodie.table.checksum"
	PropTableSchema           = "hoodie.table.schema"
	PropTimelineLayoutVersion = "hoodie.timeline.layout.version"
	PropPopulateMetaFields    = "hoodie.populate.meta.fields"
)

// TimelineLayoutVersionV1 is the timeline layout version that corresponds to hoodie.table.version 6
// and below (Hudi 0.x's classic .hoodie/-rooted timeline, no completion-time instant names). It is
// org.apache.hudi.common.table.timeline.versioning.TimelineLayoutVersion.LAYOUT_VERSION_1 in Hudi's
// own source (hudi-common 1.2.0): HoodieTableVersion.SIX maps to it directly, and
// HoodieTableMetaClient.TableBuilder#setTableVersion derives it from the table version the same way
// Java XTable's HudiTableManager does (it pins HoodieTableVersion.SIX and never overrides the
// layout). Layout version 2 (TimelineLayoutVersion.LAYOUT_VERSION_2) belongs to table version 8/9
// (Hudi 1.x's LSM-tree timeline under .hoodie/timeline), which is the version range
// MaxReadableTableVersion already refuses to read -- so a writer pinned to table version 6 must
// never emit layout version 2.
const TimelineLayoutVersionV1 = "1"

// MaxReadableTableVersion is the newest hoodie.table.version this reader understands. Hudi 1.x
// stamps version 8 or 9 and moves the timeline into .hoodie/timeline with completion-time instant
// names; reading such a table with the 0.x logic silently yields an empty snapshot, so every read
// refuses past this floor instead.
const MaxReadableTableVersion = 6

// TableProperties represents parsed key-value pairs from .hoodie/hoodie.properties.
type TableProperties struct {
	Properties map[string]string
}

// AssertReadableVersion rejects tables newer than MaxReadableTableVersion. A missing or
// unparseable version does not block: the table may predate the property, and the timeline read
// still decides.
func (p *TableProperties) AssertReadableVersion() error {
	raw := strings.TrimSpace(p.Get(PropTableVersion))
	if raw == "" {
		return nil
	}
	v, err := strconv.Atoi(raw)
	if err != nil {
		return nil
	}
	if v > MaxReadableTableVersion {
		return fmt.Errorf("hoodie.table.version %d is a Hudi 1.x table, which polytable cannot read yet (supported: version %d and older)",
			v, MaxReadableTableVersion)
	}
	return nil
}

// NewTableProperties initializes a TableProperties map.
func NewTableProperties() *TableProperties {
	return &TableProperties{
		Properties: make(map[string]string),
	}
}

// ParseProperties parses java .properties format bytes.
func ParseProperties(data []byte) (*TableProperties, error) {
	props := NewTableProperties()
	scanner := bufio.NewScanner(bytes.NewReader(data))

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			k := strings.TrimSpace(parts[0])
			v := strings.TrimSpace(parts[1])
			props.Properties[k] = v
		}
	}

	return props, scanner.Err()
}

// Serialize serializes properties into standard Java .properties format.
func (p *TableProperties) Serialize() []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by polytable\n")
	for k, v := range p.Properties {
		fmt.Fprintf(&buf, "%s=%s\n", k, v)
	}
	return buf.Bytes()
}

// Get returns the value for key or empty string.
func (p *TableProperties) Get(key string) string {
	return p.Properties[key]
}

// Set sets the value for key.
func (p *TableProperties) Set(key, value string) {
	p.Properties[key] = value
}
